### ISSUE TITLE
HACS Integration

### ISSUE THREAD

**Issue by darootler** [DavidMStraub/homeassistant-homeconnect#31]
Hi!

This is not a issue, it's more an enhancement. Would it be possible to integrate your custom component into [HACS](https://github.com/custom-components/hacs)?

As far i can see you only need to add a file called "hacs.json" to your repository with some content like [this](https://github.com/daenny/climate_group/blob/master/hacs.json).

Regards
Richard

**Comment by DavidMStraub** [comment]
Hi,

cool, I was not even aware of this. In principle, I would actually like to open a PR to get this into HA itself, but I didn't have time in the last couple of months. In the meantime, HACS looks like an interesting option.

**Comment by darootler** [comment]
If you need some testing please let me know, looks liek the effort for getting your component into HACS isn't that much.

Regards
Richard

**Comment by ltjessem** [comment]
I'd love to see it in HACS as well

**Comment by DavidMStraub** [comment]
I added the JSON file now, I think all the other requirements were already met.

Testing is welcome! I haven't installed HACS myself yet.
However note that the changes I pushed today make the component only work with HA 0.102, which is only out as beta so far.

**Comment by anthonyangel** [comment]
![Screenshot_20191119-224622](https://user-images.githubusercontent.com/2271981/69193383-79496900-0b1e-11ea-864e-baa1fef689c2.png)

Your repo can be added to HACS without the hacs.json file - not sure if it's still needed as it's not in their [integration docs](https://hacs.netlify.com/docs/publish/integration). If you want to set a minimum required Home Assistant version that now goes into manifest.json

**Comment by DavidMStraub** [comment]
Cool, didn't know. I did add 0.102 to the manifest.json.

**Comment by darootler** [comment]
I am not able to find Home Connect via HACS:

![image](https://user-images.githubusercontent.com/11849583/69230906-75523100-0b88-11ea-9def-e6b4fb2c9223.png)
![image](https://user-images.githubusercontent.com/11849583/69230955-8e5ae200-0b88-11ea-8278-e2477285d156.png)

What i am doing wrong?

Regards
Richard

**Comment by anthonyangel** [comment]
In settings you need to add https://github.com/DavidMStraub/homeassistant-homeconnect as a custom repo

**Comment by DavidMStraub** [comment]
Right, I'll submit it as a default repo once we know it works (e.g. #37).

**Comment by darootler** [comment]
> Right, I'll submit it as a default repo once we know it works (e.g. #37).

I see.

It's working now with adding a custom repository.

Regards
Richard

**Comment by DavidMStraub** [comment]
Which HACS version are you using? It's [not working](https://github.com/DavidMStraub/homeassistant-homeconnect/issues/37#issuecomment-555958143) for me yet

**Comment by darootler** [comment]
Sorry, it's also not working for me. I can install it but i am receiving the following errors:

`Component error: homeconnect - cannot import name 'CONF_CLIENT_ID' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`

`Setup failed for homeconnect: Unable to import component`

I am using HACS 0.17.3.

Regards
Richard

**Comment by DavidMStraub** [comment]
I suspect you are using HA 0.101 or earlier? The new updated integration only works with 0.102 or above (you can install `homeassistant==0.102b2` with pip if you want to try the beta version).

**Comment by darootler** [comment]
I am using HA 0.101.3 on Hass.io, i think i have to wait until 0.102 is available.

Regards
Richard

**Comment by holnburger** [comment]
Im running Home Assistant 0.102.0 and HCAS 0.17.4, all updated versions to the latest release. Adding the repository of homeconnect works fine but when i try to insall it, I get the error message:
This repository version requires Home Assistant version 0.102.0

**Comment by darootler** [comment]
> Im running Home Assistant 0.102.0 and HCAS 0.17.4, all updated versions to the latest release. Adding the repository of homeconnect works fine but when i try to insall it, I get the error message:
> This repository version requires Home Assistant version 0.102.0
> 
> Edit: 0.102.0 was released this morning

Same here.

Regards
Richard

**Comment by holnburger** [comment]
I just forked and and changed the dependent HA-version in the hcas.json, apperantly that's the only issue. Changed it to:

`{
    "name": "Home Connect",
    "domains": ["sensor", "binary_sensor", "switch"],
    "homeassistant": "0.102",
    "render_readme": true
}`

And it was working (instead of 0.102.0) - which is strange.

**Comment by DavidMStraub** [comment]
Thanks for the fix;

so is this actually working now for anyone with HA 0.102 and HA-HC 0.2.1?

For me the install silently fails and I don't know why, log:

```
Nov 21 22:00:25 hass hass[5469]: 2019-11-21 22:00:25 DEBUG (MainThread) [hacs.download.downloader] Donwloading https://raw.githubusercontent.com/DavidMStraub/homeassistant-homeconnect/v0.2.1/custom_components/homeconnect/.translations/en.json
Nov 21 22:00:25 hass hass[5469]: 2019-11-21 22:00:25 DEBUG (MainThread) [hacs.repository.integration.DavidMStraub.homeassistant-homeconnect] Downloading __init__.py
Nov 21 22:00:25 hass hass[5469]: 2019-11-21 22:00:25 DEBUG (MainThread) [hacs.download.downloader] Donwloading https://raw.githubusercontent.com/DavidMStraub/homeassistant-homeconnect/v0.2.1/custom_components/homeconnect/__init__.py
Nov 21 22:00:25 hass hass[5469]: 2019-11-21 22:00:25 ERROR (MainThread) [hacs.repository.integration.DavidMStraub.homeassistant-homeconnect] Download was not complete.
Nov 21 22:00:25 hass hass[5469]: 2019-11-21 22:00:25 ERROR (MainThread) [hacs.repository.integration.DavidMStraub.homeassistant-homeconnect] Download was not complete.
```

**Comment by DavidMStraub** [comment]
Stupid me, I didn't set 777 permissions on `custom_components`. So this issue can be closed no?

**Comment by darootler** [comment]
For me it's working now.

Thank you!

Regard
Richard

**Comment by anthonyangel** [comment]
Working for me too, FWIW it might be worth adding your repo into the default store in https://github.com/hacs/default rather than having to add it in as a custom repo

**Comment by DavidMStraub** [comment]
Right, will do this now that I know it works. Thanks!

**Comment by darootler** [comment]
> Right, will do this now that I know it works. Thanks!

Is Home Connect already in the default HACS repository?

Regards
Richard

**Comment by DavidMStraub** [comment]
No, good point. I forgot that the [PR](https://github.com/hacs/default/pull/61) wasn't merged due to a stray comma. I updated it and hope it'll be merged now.

**Comment by darootler** [comment]
Nice, i think more people will start to use/support your integration if it‘s available within the default repositories.

Regards
Richard
