### ISSUE TITLE
0.115 issues

### ISSUE THREAD

**Issue by anthonyangel** [DavidMStraub/homeassistant-homeconnect#106]
I get the following after upgrading to 0.115: `Setup failed for home_connect_beta: Unable to import component: cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`

**Comment by DavidMStraub** [comment]
Right.

https://github.com/home-assistant/core/pull/39383/files

This repo should be updated to reflect upstream changes...

**Comment by DavidMStraub** [comment]
https://github.com/home-assistant/core/tree/dev/homeassistant/components/home_connect
